name: dash_app #Environment name
dependencies:
  - python=3.7.4
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - pandas
    - numpy
    - gunicorn # for app deployment